baseURL = "http://www.codevision.cloud/"
languageCode = "en-us"
title = "Piatto della Caldaia"
theme = "hugo-theme-air"

[params]
  description = "A very beautyful site"
  cover = "static/download.jpg"
  author = "Leonardo Longhi"
  authorlocation = ""
  authorwebsite = "www.datarecipe.cloud"
  bio= "the best author of ever"
  logo = "images/user.png"
  googleAnalyticsUserID = "UA-110951718-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false